# =========================
# Servidor Render
# =========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false


spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000

# =========================
# ConfiguraÃ§Ãµes do Thymeleaf
# =========================
spring.thymeleaf.cache=false

# =========================
# InicializaÃ§Ã£o e porta
# =========================
spring.main.lazy-initialization=true
server.port=${PORT:8080}

# =========================
# Upload de arquivos
# =========================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
logging.level.org.springframework.web=DEBUG



spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# # =========================
# # Banco Local
# # =========================
# spring.datasource.url=jdbc:mysql://localhost:3306/receitas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=usbw
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # =========================
# # ConfiguraÃ§Ãµes do JPA
# # =========================
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.format_sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# spring.jpa.open-in-view=false

# spring.datasource.hikari.maximum-pool-size=3
# spring.datasource.hikari.minimum-idle=1
# spring.datasource.hikari.idle-timeout=30000
# spring.datasource.hikari.max-lifetime=60000
# spring.datasource.hikari.connection-timeout=30000

# # =========================
# # InicializaÃ§Ã£o e porta
# # =========================
# spring.main.lazy-initialization=true
# server.port=8081

# # =========================
# # Upload de arquivos
# # =========================
# spring.servlet.multipart.max-file-size=10MB
# spring.servlet.multipart.max-request-size=10MB

# # =========================
# # Configurações de Sessão
# # =========================
# server.servlet.session.cookie.same-site=lax
# server.servlet.session.cookie.http-only=true
# server.servlet.session.cookie.secure=false
# server.servlet.session.timeout=30m
# server.servlet.session.tracking-modes=cookie
